#include "AccountManager.h"
#include <iostream>
#include <algorithm>
#include <fstream>
#include <sstream>
#include <chrono>
#include <iomanip>
#include <filesystem>
#include <random>

namespace fs = std::filesystem;

AccountManager::AccountManager(const std::string& dataFilePath)
    : dataFilePath(dataFilePath) {
    // Tải dữ liệu nếu file tồn tại
    if (fs::exists(dataFilePath)) {
        loadFromFile();
    }
}

bool AccountManager::registerAccount(const User& user, const std::string& username, 
                                    const std::string& password, 
                                    AccountType type,
                                    bool isAutoGeneratedPassword) {
    // Check if username already exists
    if (usernameExists(username)) {
        std::cout << "Ten dang nhap da ton tai!" << std::endl;
        return false;
    }
    
    // Create and add new account (sử dụng mật khẩu dạng văn bản thuần)
    Account newAccount(user, username, password, type, isAutoGeneratedPassword);
    accounts.push_back(newAccount);
    
    // Lưu dữ liệu sau khi đăng ký
    saveToFile();
    
    std::cout << "Tai khoan da duoc tao thanh cong!" << std::endl;
    return true;
}

// Đăng ký tài khoản với mật khẩu tự động sinh
std::string AccountManager::registerAccountWithAutoPassword(const User& user, const std::string& username,
                                                      AccountType type) {
    // Sinh mật khẩu tự động (không dùng PasswordHasher)
    std::string autoPassword = generateRandomPassword();
    
    // Đăng ký tài khoản với mật khẩu tự sinh
    if (registerAccount(user, username, autoPassword, type, true)) {
        return autoPassword; // Trả về mật khẩu đã sinh để hiển thị cho người dùng
    }
    
    return ""; // Trường hợp đăng ký thất bại
}

// Phương thức sinh mật khẩu ngẫu nhiên (thay thế PasswordHasher::generatePassword)
std::string AccountManager::generateRandomPassword(size_t length) {
    const char charset[] = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!@#$%^&*";
    const size_t charset_size = sizeof(charset) - 1;
    
    std::random_device rd;
    std::mt19937 generator(rd());
    std::uniform_int_distribution<int> distribution(0, charset_size - 1);
    
    std::string password;
    password.reserve(length);
    for (size_t i = 0; i < length; ++i) {
        password += charset[distribution(generator)];
    }
    return password;
}

// Đăng nhập với debug
bool AccountManager::login(const std::string& username, const std::string& password) {
    std::cout << "Dang kiem tra dang nhap cho tai khoan: " << username << std::endl;
    
    Account* account = findAccount(username);
    
    if (!account) {
        std::cout << "Ten dang nhap khong ton tai!" << std::endl;
        return false;
    }
    
    std::cout << "Da tim thay tai khoan, dang kiem tra mat khau..." << std::endl;
    
    if (!account->isAccountActive()) {
        std::cout << "Tai khoan da bi khoa!" << std::endl;
        return false;
    }
    
    // Thêm thông tin debug
    std::cout << "Mat khau nhap vao: " << password << std::endl;
    
    bool validPassword = account->validatePassword(password);
    std::cout << "Ket qua xac thuc mat khau: " << (validPassword ? "Thanh cong" : "That bai") << std::endl;
    
    if (!validPassword) {
        std::cout << "Mat khau khong chinh xac!" << std::endl;
        return false;
    }
    
    // Đăng nhập thành công
    currentLoggedInUser = username;
    
    if (account->isPasswordAutoGenerated()) {
        std::cout << "Ban dang su dung mat khau tu dong sinh. Vui long doi mat khau ngay!" << std::endl;
    }
    
    std::cout << "Dang nhap thanh cong!" << std::endl;
    return true;
}

// Đổi mật khẩu với xác thực
bool AccountManager::changePassword(const std::string& username, const std::string& oldPassword, 
                                  const std::string& newPassword) {
    Account* account = findAccount(username);
    
    if (!account) {
        std::cout << "Ten dang nhap khong ton tai!" << std::endl;
        return false;
    }
    
    if (!account->validatePassword(oldPassword)) {
        std::cout << "Mat khau cu khong chinh xac!" << std::endl;
        return false;
    }
    
    // Đổi mật khẩu (sử dụng mật khẩu dạng văn bản thuần)
    account->setPassword(newPassword, false); // false = không phải mật khẩu tự sinh
    saveToFile(); // Lưu thay đổi
    
    std::cout << "Da doi mat khau thanh cong!" << std::endl;
    return true;
}

// Đổi mật khẩu bắt buộc (không cần mật khẩu cũ)
bool AccountManager::forceChangePassword(const std::string& username, const std::string& newPassword) {
    Account* account = findAccount(username);
    
    if (!account) {
        std::cout << "Ten dang nhap khong ton tai!" << std::endl;
        return false;
    }
    
    // Đổi mật khẩu (sử dụng mật khẩu dạng văn bản thuần)
    account->setPassword(newPassword, false); // false = không phải mật khẩu tự sinh
    saveToFile(); // Lưu thay đổi
    
    std::cout << "Da doi mat khau thanh cong!" << std::endl;
    return true;
}

bool AccountManager::usernameExists(const std::string& username) const {
    return std::any_of(accounts.begin(), accounts.end(), 
                      [&username](const Account& acc) { 
                          return acc.getUsername() == username; 
                      });
}

Account* AccountManager::findAccount(const std::string& username) {
    std::cout << "Tim kiem tai khoan voi username: '" << username << "'" << std::endl;
    std::cout << "So luong tai khoan hien co: " << accounts.size() << std::endl;
    
    for (auto& account : accounts) {
        std::cout << "Kiem tra tai khoan: '" << account.getUsername() << "'" << std::endl;
        if (account.getUsername() == username) {
            std::cout << "Da tim thay tai khoan!" << std::endl;
            return &account;
        }
    }
    
    std::cout << "Khong tim thay tai khoan!" << std::endl;
    return nullptr;
}

void AccountManager::displayAllAccounts() const {
    if (accounts.empty()) {
        std::cout << "Khong co tai khoan nao!" << std::endl;
        return;
    }
    
    std::cout << "=== Danh sach tai khoan ===" << std::endl;
    for (const auto& account : accounts) {
        account.displayInfo();
        std::cout << "------------------------" << std::endl;
    }
}

bool AccountManager::loadFromFile(const std::string& filename) {
    std::string loadFilename = filename.empty() ? dataFilePath : filename;
    
    try {
        if (!fs::exists(loadFilename)) {
            std::cerr << "File khong ton tai: " << loadFilename << std::endl;
            return false;
        }
        
        std::cout << "Bat dau tai du lieu tu file: " << loadFilename << std::endl;
        
        std::ifstream file(loadFilename);
        if (!file.is_open()) {
            std::cerr << "Khong the mo file de doc: " << loadFilename << std::endl;
            return false;
        }
        
        size_t accountCount;
        file >> accountCount;
        file.ignore();
        
        std::cout << "So luong tai khoan can tai: " << accountCount << std::endl;
        
        accounts.clear();
        
        for (size_t i = 0; i < accountCount; ++i) {
            std::string accountStr;
            std::getline(file, accountStr);
            if (!accountStr.empty()) {
                std::cout << "Doc dong tai khoan thu " << i+1 << ": " << accountStr << std::endl;
                
                Account account = Account::fromString(accountStr);
                std::cout << "Username doc duoc: " << account.getUsername() << std::endl;
                
                accounts.push_back(account);
            }
        }
        
        file.close();
        
        std::cout << "Da tai " << accounts.size() << " tai khoan." << std::endl;
        
        // Hiển thị tất cả tài khoản đã tải
        std::cout << "=== Tai khoan da tai ===" << std::endl;
        for (const auto& acc : accounts) {
            std::cout << "Username: " << acc.getUsername() << std::endl;
        }
        
        return true;
    } catch (const std::exception& e) {
        std::cerr << "Loi khi tai du lieu: " << e.what() << std::endl;
        return false;
    }
}

bool AccountManager::saveToFile(const std::string& filename) const {
    std::string saveFilename = filename.empty() ? dataFilePath : filename;
    
    try {
        std::ofstream file(saveFilename);
        if (!file.is_open()) {
            std::cerr << "Khong the mo file de luu: " << saveFilename << std::endl;
            return false;
        }
        
        file << accounts.size() << std::endl;
        
        for (const auto& account : accounts) {
            file << account.toString() << std::endl;
        }
        
        file.close();
        
        std::cout << "Da luu du lieu vao: " << saveFilename << std::endl;
        return true;
    } catch (const std::exception& e) {
        std::cerr << "Loi khi luu du lieu: " << e.what() << std::endl;
        return false;
    }
}

bool AccountManager::backupData() const {
    fs::create_directories("backups");
    
    auto now = std::chrono::system_clock::now();
    auto timestamp = std::chrono::system_clock::to_time_t(now);
    std::stringstream ss;
    ss << "backups/accounts_" << std::put_time(std::localtime(&timestamp), "%Y%m%d_%H%M%S") << ".txt";
    std::string backupFilename = ss.str();
    
    bool success = saveToFile(backupFilename);
    
    if (success) {
        std::cout << "Da sao luu du lieu vao: " << backupFilename << std::endl;
        const_cast<AccountManager*>(this)->rotateBackups();
    }
    
    return success;
}

bool AccountManager::restoreFromBackup(const std::string& backupFilename) {
    if (!fs::exists(backupFilename)) {
        std::cout << "File sao luu khong ton tai!" << std::endl;
        return false;
    }
    
    backupData();
    
    bool success = loadFromFile(backupFilename);
    
    if (success) {
        saveToFile();
        std::cout << "Da phuc hoi du lieu tu: " << backupFilename << std::endl;
    } else {
        std::cout << "Khong the phuc hoi du lieu!" << std::endl;
    }
    
    return success;
}

void AccountManager::displayBackups() const {
    auto backups = listBackups();
    
    if (backups.empty()) {
        std::cout << "Khong co ban sao luu nao!" << std::endl;
        return;
    }
    
    std::cout << "=== Danh sach ban sao luu ===" << std::endl;
    for (size_t i = 0; i < backups.size(); ++i) {
        std::cout << i + 1 << ". " << backups[i] << std::endl;
    }
}

std::vector<std::string> AccountManager::listBackups() const {
    std::vector<std::string> backupFiles;
    
    if (!fs::exists("backups")) {
        return backupFiles;
    }
    
    for (const auto& entry : fs::directory_iterator("backups")) {
        if (entry.is_regular_file() && entry.path().extension() == ".txt") {
            backupFiles.push_back(entry.path().string());
        }
    }
    
    std::sort(backupFiles.begin(), backupFiles.end(), std::greater<>());
    
    return backupFiles;
}

void AccountManager::rotateBackups(int keepCount) {
    auto backupFiles = listBackups();
    
    if (backupFiles.size() > keepCount) {
        for (size_t i = keepCount; i < backupFiles.size(); ++i) {
            fs::remove(backupFiles[i]);
            std::cout << "Da xoa ban sao luu cu: " << backupFiles[i] << std::endl;
        }
    }
}